# Use an official Node runtime as a parent image
FROM node:20-alpine

# Set environment variables
ENV NODE_ENV=production

# Set work directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Define the command to run the application
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--port", "3000"]