import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Default sidebar - AI-Native Development Book
  docs: [
    {
      type: 'category',
      label: 'AI-Native ترقی کی کتاب',
      items: [
        'chapters/chapter1-introduction',
        'chapters/chapter2-llms',
        'chapters/chapter3-building-applications',
        'chapters/chapter4-tools-frameworks',
        'chapters/chapter5-practical-examples',
        'chapters/chapter6-deployment-production',
        'chapters/chapter7-monitoring-maintenance',
        'chapters/chapter8-security-privacy-ethics',
        'chapters/chapter9-future-trends-conclusion'
      ],
    },
  ],

  // Tutorial sidebar (if needed)
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;